

export function setLanguage() {
    const language = sessionStorage.getItem('language');
    if (language === "persian") {
        const language = {
            rtl: true,
            home: "خانه",
            Credit: "اعتباری",
            Permanent: "دائمی",
            hourly: "ساعتی",
            Daily: "روزانه",
            threeDaily: "3 روزه",
            fourMonths: "4 ماهه",
            twoMonthly: "2 ماهه",
            Weekly: "هفتگی",
            monthly: "ماهانه",
            sixMonths: "6 ماه",
            threeMonths: "3 ماهه",
            yearly: "سالانه",
            services: "خدمات",
            aboutUs: "تماس با ما",
            rules: "قوانین",
            chargeStore: "آیسان پرداخت",
            typeOfRequest: "نوع درخواست",
            completeInformation: "تکمیل اطلاعات",
            payment: "پرداخت نهایی",
            charge: "شارژ مستقیم",
            internetPack: "بسته اینترنت",
            bill: "پرداخت قبض",
            pay: "پرداخت",
            amazingCharge: " شگفت انگیز",
            mobileNumber: "شماره موبایل خریدار",
            subscriberNumber: "شماره موبایل ذینفع",
            nationalCode: "شماره ملی خریدار",
            postalCode: "کد پستی خریدار",
            doHezar: "۲,۰۰۰ تومان",
            panjHezar: "۵,۰۰۰ تومان",
            dahHezar: "۱۰,۰۰۰ تومان",
            bistHezar: "۲۰,۰۰۰ تومان",
            panjaHezar: "۵۰,۰۰۰ تومان",
            sadHezar: "۱۰۰,۰۰۰ تومان",
            typeOfSim: "نوع سیمکارت",
            internetPeriod: "مدت بسته",
            chooseInternetPeriod: "انتخاب بسته",
            billId: "شناسه قبض",
            paymentId: "شناسه پرداخت",
            confirm: "تایید",
            price: "قیمت (تومان)",
            PaymentGateway: "درگاه پرداخت",
            bio: "(خرید با کلیه کارتهای بانکی امکان پذیر است)",
            footer: "تمامی حقوق این سایت محفوظ میباشید",
            waterBill: "قبض آب",
            ElectricBill: "قبض برق",
            gasBill: "قبض گاز",
            LandlinePhoneBill: "قبض تلفن ثابت",
            PhoneBill: "قبض موبایل همراه",
            mciCharge: "شارژ همراه اول",
            samantelCharge: "شارژ سامانتل",
            rightelCharge: "شارژ رایتل",
            mciNetPack: "بسته همراه اول",
            samantelNetPack: "بسته سامانتل",
            rightelNetPack: "بسته رایتل",
            irancellNetPack: "بسته ایرانسل",
            ruleTitle: "قوانین استفاده از خدمات فروشگاه",
            choose: "انتخاب کنید",
            ruleItems: [
                "تمامی حقوق مادی و معنوی این وبسایت متعلق به شرکت خدمات همراه آیسان می باشد.",
                "سرویس های ارائه شده در این وبسایت با مجوز از تمامی از ارگان‌ها و سازمان‌های نظارتی ارائه شده است.",
                "هرگونه اشتباه در وارد کردن اطلاعات توسط مشتریان بر عهده مشتریان می باشد.",
                "شرکت آیسان حق هرگونه تغییر و یا حذف سرویس را برای خود محفوظ می‌داند.",
                "شرکت آیسان وظیفه دارد تا در صورت تایید پرداخت توسط شبکه شاپرک سرویس مورد نظر مشتری را اعم از پرداخت قبض، شارژ و‌... در اسرع وقت ارائه نماید. در غیر اینصورت ظرف مدت 72 ساعت نسبت به عودت وجه به مشتری مورد نظر اقدام خواهد شد.",
                "در صورتی که مبلغ مورد نظر سرویس از حساب مشتریان کسر و سرویس مورد نظر به مشتری ارائه شود مراجع تایید ارائه سرویس اپراتور سرویس دهنده یا سازمان ارائه دهنده سرویس می باشند. در صورت استعلام و تایید شدن ارائه سرویس آیسان مسولیتی در قبال عدم ارائه سرویس نخواهد داشت.",
                "تمامی اطلاعات پرداخت اعم از شماره کارت، رمز اینترنتی و.... توسط شبکه شاپرک دریافت خواهد شد و آیسان حق هیچ گونه ذخیره سازی در این مورد را نخواهد داشت.",
                "استفاده از سرویس‌های وبسایت به منزله پذیرفتن قوانین و هم چنین عضویت در لیست مشتریان شرکت آیسان می‌باشد."
            ],
            contactItems: " جهت تماس با ما می توانید از راه های زیر اقدام فرمایید.\n" +
            "تلفن پشتیبانی : 021-22924567\n" +
            "نمابر : 22906883\n" +
            "ایمیل : info@isuncorp.com\n" +
            "تلگرام : 09100051482\n" +
            "نشانی : تهران - خیابان ظفر - پلاک 262 - طبقه 3 - واحد 8"
        };
        return language;

    }
    else if (language === "turkish") {
        const language = {
            rtl: true,
            home: "منزیل",
            Credit: "اعتباری",
            Permanent: "دائمی",
            hourly: "ساعا تلیق",
            Daily: "گونلوق",
            threeDaily: "3 گونلوق",
            fourMonths: "4 آیلیق",
            twoMonthly: "2 آیلیق",
            Weekly: "هفته لیک",
            monthly: "آیلیق",
            sixMonths: "6آیلیق",
            threeMonths: "3آیلیق",
            yearly: "ایل لیک",
            aboutUs: "بیزینن ارتباطات گچ",
            rules: "قانون لار",
            chargeStore: "آیسان پرداخت",
            typeOfRequest: "ایستک نوعی",
            completeInformation: "معلوماتی تامام لا",
            payment: "نهایی اودمه",
            charge: "مستقیم شارژ",
            internetPack: "اینترنت بسته سی",
            bill: "قبض اودمه",
            pay: "اودمه",
            amazingCharge: " شگفت انگیز",
            mobileNumber: "آلانین موبایل شماره سی",
            subscriberNumber: "ذینفعین موبایل شماره",
            nationalCode: "آلانین ملی شماره سی",
            postalCode: "آلانین پستی کودو",
            doHezar: "۲,۰۰۰ تومان",
            panjHezar: "۵,۰۰۰ تومان",
            dahHezar: "۱۰,۰۰۰ تومان",
            bistHezar: "۲۰,۰۰۰ تومان",
            panjaHezar: "۵۰,۰۰۰ تومان",
            sadHezar: "۱۰۰,۰۰۰ تومان",
            typeOfSim: "سیم کارت مدلی",
            internetPeriod: "بسته نین زامانی",
            chooseInternetPeriod: "بسته نی سئیچ",
            billId: "قبضین شناسه سی",
            paymentId: "پرداخت شناسه سی",
            confirm: "اونایلا",
            price: "قیمت (تومان)",
            PaymentGateway: "بانکی درگاه",
            bio: "(تامام کارت لارینان آلا بیلرسیز)",
            footer: "بوسایتین تامام حق لری حفظ اولونوپ",
            waterBill: "سو قبضی",
            ElectricBill: "الکتریک قبضی",
            gasBill: "گاز قبضی",
            LandlinePhoneBill: "ثابت تلفن قبضی",
            PhoneBill: "موبایل قبضی",
            mciCharge: "همراه اول شارژی",
            samantelCharge: "سامانتل شارژی",
            rightelCharge: "رایتل شارژی",
            mciNetPack: "همراه اول بسته سی",
            samantelNetPack: "سامانتل بسته سی",
            rightelNetPack: "رایتل بسته سی",
            irancellNetPack: "ایرانسل بسته سی",
            ruleTitle: "توکانین استفاده قانون لاری",
            choose: "سئچین",
            ruleItems: [
                "تمامی حقوق مادی و معنوی این وبسایت متعلق به شرکت خدمات همراه آیسان می باشد.",
                "سرویس های ارائه شده در این وبسایت با مجوز از تمامی از ارگان‌ها و سازمان‌های نظارتی ارائه شده است.",
                "هرگونه اشتباه در وارد کردن اطلاعات توسط مشتریان بر عهده مشتریان می باشد.",
                "شرکت آیسان حق هرگونه تغییر و یا حذف سرویس را برای خود محفوظ می‌داند.",
                "شرکت آیسان وظیفه دارد تا در صورت تایید پرداخت توسط شبکه شاپرک سرویس مورد نظر مشتری را اعم از پرداخت قبض، شارژ و‌... در اسرع وقت ارائه نماید. در غیر اینصورت ظرف مدت 72 ساعت نسبت به عودت وجه به مشتری مورد نظر اقدام خواهد شد.",
                "در صورتی که مبلغ مورد نظر سرویس از حساب مشتریان کسر و سرویس مورد نظر به مشتری ارائه شود مراجع تایید ارائه سرویس اپراتور سرویس دهنده یا سازمان ارائه دهنده سرویس می باشند. در صورت استعلام و تایید شدن ارائه سرویس آیسان مسولیتی در قبال عدم ارائه سرویس نخواهد داشت.",
                "تمامی اطلاعات پرداخت اعم از شماره کارت، رمز اینترنتی و.... توسط شبکه شاپرک دریافت خواهد شد و آیسان حق هیچ گونه ذخیره سازی در این مورد را نخواهد داشت.",
                "استفاده از سرویس‌های وبسایت به منزله پذیرفتن قوانین و هم چنین عضویت در لیست مشتریان شرکت آیسان می‌باشد."
            ],
            contactItems:
            "تلفن پشتیبانی : 021-22924567\n" +
            "نمابر : 22906883\n" +
            "ایمیل : info@isuncorp.com\n" +
            "تلگرام : 09100051482\n" +
            "نشانی : تهران - خیابان ظفر - پلاک 262 - طبقه 3 - واحد 8"
        };
        return language;
    }
    else if (language === "arabic") {
        const language = {
            rtl: true,
            home: "الصفحه الرئیسیه",
            Credit: "ائتمان",
            Permanent: "مستمر",
            hourly: "باستمرار",
            Daily: "يوميا",
            threeDaily: "3 ايام",
            fourMonths: "4 شهور",
            twoMonthly: "شهرين",
            Weekly: "أسبوعيا",
            monthly: "شهريا",
            sixMonths: "6اشهر",
            threeMonths: "3اشهر",
            yearly: "سنوي",
            aboutUs: "اتصل بنا",
            rules: "قوانين",
            chargeStore: "ایسان پرداخت",
            typeOfRequest: "نوع من المطالب",
            completeInformation: "أكمل المعلومات",
            payment: "آخر دفعه",
            charge: "الشحن المباشر",
            internetPack: "حزمة الإنترنت",
            bill: "دفع الفاتورة",
            pay: "دفع",
            amazingCharge: "رائعه",
            mobileNumber: "رقم الجوال للمشتري",
            subscriberNumber: "رقم هاتف المستفيد",
            nationalCode: "رقم المشتري الوطني",
            postalCode: "الرمز البريدي للمشتري",
            doHezar: "۲,۰۰۰ تومان",
            panjHezar: "۵,۰۰۰ تومان",
            dahHezar: "۱۰,۰۰۰ تومان",
            bistHezar: "۲۰,۰۰۰ تومان",
            panjaHezar: "۵۰,۰۰۰ تومان",
            sadHezar: "۱۰۰,۰۰۰ تومان",
            typeOfSim: "نوع SIM",
            internetPeriod: "مصطلح مغلق",
            chooseInternetPeriod: "اختيار الحزمة",
            billId: "معرف الفاتورة",
            paymentId: "معرف الدفع",
            confirm: "التأكيد",
            price: "السعر(تومان)",
            PaymentGateway: "قناه الفع",
            bio: "(متوفر مع جميع البطاقات المصرفية المتاحة)",
            footer: "جميع الحقوق محفوظة",
            waterBill: "فاتورة الماء",
            ElectricBill: "فاتورة الكهرباء",
            gasBill: "فاتورة الغاز",
            LandlinePhoneBill: "فاتورة الهاتف الثابت",
            PhoneBill: "فاتورة الجوال",
            mciCharge: "شحن MCI",
            samantelCharge: "شحن Samantel",
            rightelCharge: "شحن Rightel",
            mciNetPack: "الانترنت MCI",
            samantelNetPack: "الانترنت Samantel",
            rightelNetPack: "الانترنت rightel",
            irancellNetPack: "الانترنت Irancell",
            ruleTitle: "شروط الخدمة متجر",
            contactTitle: "",
            choose: "اختر",
            ruleItems: [
                "تمامی حقوق مادی و معنوی این وبسایت متعلق به شرکت خدمات همراه آیسان می باشد.",
                "سرویس های ارائه شده در این وبسایت با مجوز از تمامی از ارگان‌ها و سازمان‌های نظارتی ارائه شده است.",
                "هرگونه اشتباه در وارد کردن اطلاعات توسط مشتریان بر عهده مشتریان می باشد.",
                "شرکت آیسان حق هرگونه تغییر و یا حذف سرویس را برای خود محفوظ می‌داند.",
                "شرکت آیسان وظیفه دارد تا در صورت تایید پرداخت توسط شبکه شاپرک سرویس مورد نظر مشتری را اعم از پرداخت قبض، شارژ و‌... در اسرع وقت ارائه نماید. در غیر اینصورت ظرف مدت 72 ساعت نسبت به عودت وجه به مشتری مورد نظر اقدام خواهد شد.",
                "در صورتی که مبلغ مورد نظر سرویس از حساب مشتریان کسر و سرویس مورد نظر به مشتری ارائه شود مراجع تایید ارائه سرویس اپراتور سرویس دهنده یا سازمان ارائه دهنده سرویس می باشند. در صورت استعلام و تایید شدن ارائه سرویس آیسان مسولیتی در قبال عدم ارائه سرویس نخواهد داشت.",
                "تمامی اطلاعات پرداخت اعم از شماره کارت، رمز اینترنتی و.... توسط شبکه شاپرک دریافت خواهد شد و آیسان حق هیچ گونه ذخیره سازی در این مورد را نخواهد داشت.",
                "استفاده از سرویس‌های وبسایت به منزله پذیرفتن قوانین و هم چنین عضویت در لیست مشتریان شرکت آیسان می‌باشد."
            ],
            contactItems:
            "الدعم عبر الهاتف : 021-22924567\n" +
            "الموقع : 22906883\n" +
            "البريد الإلكتروني : info@isuncorp.com\n" +
            "تلگرام : 09100051482\n" +
            "عنوان : تهران - شارع ظفر - لوحة 262 - فئة 3 - وحدة 8"
        };
        return language;
    }
    else if (language === "english") {
        const language = {
            rtl: false,
            home: "home",
            Credit: "pre Paid",
            Permanent: "post Paid",
            Daily: "daily",
            hourly: "hourly",
            Weekly: "weekly",
            threeDaily: "3 days",
            fourMonths: "4 months",
            twoMonthly: "2 months",
            monthly: "monthly",
            sixMonths: "6 months",
            threeMonths: "3 months",
            yearly: "yearly",
            services: "services",
            aboutUs: "contact us",
            rules: "rules",
            chargeStore: "ISUNCHARGE ",
            typeOfRequest: "type of request",
            completeInformation: "extra  information",
            payment: "payment",
            charge: "direct charge",
            internetPack: "internet package",
            bill: "paying bill ",
            amazingCharge: "amazing charge",
            mobileNumber: "mobile number",
            subscriberNumber: "subscriber number",
            nationalCode: "national code",
            postalCode: "postal code",
            doHezar: " 2,000 ",
            panjHezar: " 5,000",
            dahHezar: " 10,000",
            bistHezar: " 20,000",
            panjaHezar: " 50,000",
            sadHezar: " 100,000",
            typeOfSim: "type of simcard",
            internetPeriod: "internet period",
            chooseInternet: "choose package",
            billId: "bill ID",
            paymentId: "payment ID",
            confirm: "confirm",
            price: "(toman) price ",
            pay: "pay",
            PaymentGateway: "Payment gateway",
            bio: "(It's possible to purchase with all bank cards)",
            footer: "All rights reserved",
            waterBill: "water bill",
            ElectricBill: "electric bill",
            gasBill: "gas bill",
            LandlinePhoneBill: "landline phone bill",
            PhoneBill: "phone bill",
            mciCharge: "mci charge",
            samantelCharge: "samantel charge",
            rightelCharge: "rightel charge",
            mciNetPack: "mci internet",
            samantelNetPack: "samantel internet",
            rightelNetPack: "rightel internet",
            irancellNetPack: "irancell internet",
            chooseInternetPeriod: "choose internet",
            ruleItems: [
                "All intellectual property rights in this website are owned by ISUN Mobile Service Company", "The services provided on this website are provided with the authorization of all regulatory agencies", "Customers will be liable for any misstatement of customer information",
                "ISUN reserves the right to change or delete any service","Use of the Website Services constitutes acceptance of the rules and is also a subscription to ISUN's customer list"
            ],
            contactTitle: "contact us",
            choose: "choose",
            ruleTitle: "terms and conditions",
            contactItems: " Support phone : 021-22924567\n" +
            "Fax : 22906883\n"+"email : info@isuncorp.com\n"+"telegram : 09100051482\n"+"address : tehran/zafar street/Plaque262/third floor/Unit Eight\n"


        };
        return language;
    };
}


